import { v4 as uuid } from "uuid";

import {
  headphone1,
  headphone2,
  laptop1,
  laptop2,
  mobile,
  smartwatch1,
  smartwatch,
  speaker,
  speaker1,
  storage,
  storage1,
} from "assets";

export const products = [
  {
    _id: uuid(),
    title: "Marshall Headphones",
    description: "Wireless Bluetooth Headphone Over Ear, Voice Control, Black",
    originalPrice: 799,
    discountedPrice: 599,
    discountPercent: 25,
    categoryName: "Headphones",
    image: headphone1,
    altText: "Marshall Headphones",
    rating: 4.1,
  },
  {
    _id: uuid(),
    title: "Gigabyte Speakers",
    description: "4.1 channel multimedia speakers, TYPE: Bass Reflex",
    originalPrice: 8999,
    discountedPrice: 7199,
    discountPercent: 20,
    categoryName: "Speakers",
    image: speaker,
    altText: "Gigabyte Speakers",
    rating: 4.5,
  },
  {
    _id: uuid(),
    title: "Beats Studio",
    description:
      "On-ear lightweight Headphones with high bass and noise cancellation",
    originalPrice: 799,
    discountedPrice: 599,
    discountPercent: 25,
    categoryName: "Headphones",
    image: headphone2,
    altText: "Beats Studio",
    rating: 3.5,
  },
  {
    _id: uuid(),
    title: "Noise Smartwatch",
    description:
      "Mini Smart Watch with SpO2 Level Measurement and 70+ Sports Modes",
    originalPrice: 9999,
    discountedPrice: 6999,
    discountPercent: 30,
    categoryName: "Smartwatches",
    image: smartwatch1,
    altText: "Noise Smartwatch",
    rating: 4.2,
  },
  {
    _id: uuid(),
    title: "Fire-Boltt Smartwatch",
    description: "Fire-Boltt SpO2 Full Touch 1.4 inch Smart Watch 400",
    originalPrice: 5999,
    discountedPrice: 2499,
    discountPercent: 58,
    categoryName: "Smartwatches",
    image: smartwatch,
    altText: "Fire-Boltt Smartwatch",
    rating: 2.9,
  },
  {
    _id: uuid(),
    title: "JBL Speakers",
    description:
      "Amplify your listening experience with premium speakers from JBL",
    originalPrice: 15999,
    discountedPrice: 13999,
    discountPercent: 13,
    categoryName: "Speakers",
    image: speaker1,
    altText: "JBL Speakers",
    rating: 3.2,
  },
  {
    _id: uuid(),
    title: "Dell Laptop",
    description: "i5-1135G7, 16GB / 512GB SSD, Win 11+MSO'21, 14” Display",
    originalPrice: 81882,
    discountedPrice: 58390,
    discountPercent: 29,
    categoryName: "Laptops",
    image: laptop1,
    altText: "Dell Laptop",
    rating: 4.5,
  },
  {
    _id: uuid(),
    title: "Samsung Portable SSD",
    description:
      "Up to 540MB/s USB 3.1 Gen 2 External Solid State Drive Deep  - Black",
    originalPrice: 28599,
    discountedPrice: 10499,
    discountPercent: 63,
    categoryName: "Storage Devices",
    image: storage,
    altText: "Samsung Portable SSD",
    rating: 3.9,
  },
  {
    _id: uuid(),
    title: "Apple iPhone 11",
    description:
      "Liquid HD display, A13 Bionic chip with third-generation Neural Engine",
    originalPrice: 49900,
    discountedPrice: 47990,
    discountPercent: 4,
    categoryName: "Mobiles",
    image: mobile,
    altText: "Apple iPhone 11",
    rating: 4.7,
  },
  {
    _id: uuid(),
    title: "WD Hard Drive",
    description: "Western Digital Purple 1TB Surveillance Hard Drive",
    originalPrice: 4800,
    discountedPrice: 3320,
    discountPercent: 31,
    categoryName: "Storage Devices",
    image: storage1,
    altText: "WD Hard Drive",
    rating: 4.0,
  },
  {
    _id: uuid(),
    title: "Apple Macbook",
    description:
      "13.3-inch Retina Display, 8GB RAM, 256GB SSD Storage, Touch ID.",
    originalPrice: 92900,
    discountedPrice: 84990,
    discountPercent: 9,
    categoryName: "Laptops",
    image: laptop2,
    altText: "Apple Macbook",
    rating: 4.7,
  },
];
